fragment UserAttributes on User {
  _id
  name {
    first
    last
  }
  username
  emailAddress
  oAuthProvider
  roles {
    _id
    name
    inRole
  }
  settings {
    gdprCanSendMarketingEmails
  }
}
