fragment UserAttributes on User {
  _id
  profile {
    firstName
    lastName
  }
  username
  emailAddress
  oAuthProvider
  roles {
    _id
    name
    inRole
  }
  settings {
    gdpr {
      canSendMarketingEmails
      #### PLOP_USER_SETTINGS_GDPR_START ####
      #### PLOP_USER_SETTINGS_GDPR_END ####
    }
    #### PLOP_USER_SETTINGS_START ####
    #### PLOP_USER_SETTINGS_END ####
  }
}
