fragment UserAttributes on User {
  _id
  profile {
    firstName
    lastName
  }
  username
  emailAddress
  oAuthProvider
  roles {
    _id
    name
    inRole
  }
  settings {
    gdprCanSendMarketingEmails
  }
}
