# scalar DateTime
# scalar Time
# scalar Date
# scalar ObjectID

type UsersRole {
  _id: String
  name: String
  createdAt: DateTime
  createdById: String
  createdBy: User
  updatedAt: DateTime
  updatedById: String
  updatedBy: User
}

type UsersRoles {
  total: Int
  usersRoles: [UsersRole]
}

input UsersRoleInput {
  _id: String
  name: String!
}

type Query {
  usersRoles(
    _ids: [String]
    page: Int
    pageSize: Int
    sort: String
    order: String
    search: String
  ): UsersRoles
  myUsersRoles: [UsersRole]
  usersRole(_id: String, name: String): UsersRole
}

type Mutation {
  saveUsersRole(usersRole: UsersRoleInput): UsersRole
  removeUsersRole(_id: String!): UsersRole
}