fragment ErrorReportAttributes on ErrorReport {
  _id
  userId
  user {
    fullName
  }
  level
  message
  path
  userAgent
  stack
  reactStack
  createdAtUTC
  createdById
  createdBy {
    fullName
  }
}


