fragment ErrorReportAttributes on ErrorReport {
  _id
  _id
  user { 
    _id
    fullName
  }
  userId
  level
  level
  message
  message
  path
  path
  userAgent
  userAgent
  stack
  stack
  reactStack
  reactStack
  createdAtUTC
  createdBy { 
    _id
    fullName
  }
}
