fragment ErrorReportAttributes on ErrorReport {
  _id
  user { 
    _id
    fullName
  }
  userId
  level
  message
  path
  userAgent
  stack
  reactStack
  createdAtUTC
  createdBy { 
    _id
    fullName
  }
}


