#import "./fragments.gql"

query USERS_QUERY($page: Int, $pageSize: Int, $search: String, $sort: String, $order: String, $role: [String]) {
  users(page: $page, pageSize: $pageSize, search: $search, sort: $sort, order: $order, role: $role) {
    total
    users {
      _id
      fullName
      username
      emailAddress
      oAuthProvider
      roles
    }
  }
}

query USER_QUERY($_id: String) {
  user(_id: $_id) {
    ...UserAttributes
  }
}

query USER_SETTINGS_QUERY {
  user {
    settings {
      gdpr {
      canSendMarketingEmails
      #### PLOP_USER_SETTINGS_GDPR_START ####
      #### PLOP_USER_SETTINGS_GDPR_END ####
    }
    #### PLOP_USER_SETTINGS_START ####
    #### PLOP_USER_SETTINGS_END ####
    }
  }
}

query EXPORT_USER_DATA_QUERY {
  exportUserData {
    zip
  }
}

query OAUTH_SERVICES_QUERY($services: [String]) {
  oAuthServices(services: $services)
}

