#import "../fragments/Users.gql"

query users($page: Int, $pageSize: Int, $search: String, $sort: String, $order: String, $role: [String]) {
  users(page: $page, pageSize: $pageSize, search: $search, sort: $sort, order: $order, role: $role) {
    total
    users {
      _id
      fullName
      username
      emailAddress
      oAuthProvider
      roles
    }
  }
}

query user($_id: String) {
  user(_id: $_id) {
    ...UserAttributes
  }
}

query userSettings {
  user {
    settings {
      gdpr {
      canSendMarketingEmails
      #### PLOP_USER_SETTINGS_GDPR_START ####
      #### PLOP_USER_SETTINGS_GDPR_END ####
    }
    #### PLOP_USER_SETTINGS_START ####
    #### PLOP_USER_SETTINGS_END ####
    }
  }
}

query exportUserData {
  exportUserData {
    zip
  }
}
