#import "../fragments/ErrorReports.gql"

query errorReports($page: Int, $pageSize: Int, $search: String, $sort: String, $order: String, $level: [Int]) {
  errorReports(page: $page, pageSize: $pageSize, search: $search, sort: $sort, order: $order, level: $level) {
    total
    errorReports {
    ...ErrorReportAttributes
    }
  }
}

query editErrorReport($_id: String) {
  errorReport(_id: $_id) {
    ...ErrorReportAttributes
  }
}

query errorReport($_id: String) {
  errorReport(_id: $_id) {
    ...ErrorReportAttributes
  }
}
