#import "../fragments/ErrorReports.gql"

query errorReports(
  $_ids: [String]
  $page: Int, 
  $pageSize: Int, 
  $search: String, 
  $sort: String, 
  $order: String,
  $level: [Int],
) {
  errorReports(
    _ids: $_ids,
    page: $page, 
    pageSize: $pageSize, 
    search: $search, 
    sort: $sort, 
    order: $order,
    level: $level,
  ) {
    total
    errorReports {
      _id
      
      user {
              fullName
            }
      level
      message
      path
      userAgent
      createdAtUTC
    }
  }
}

query editErrorReport($_id: ObjectID) {
  errorReport(_id: $_id) {
    ...ErrorReportAttributes
  }
}

query errorReport($_id: ObjectID) {
  errorReport(_id: $_id) {
    ...ErrorReportAttributes
  }
}
