type Comment {
  _id: String
  userId: String
  user: User
  documentId: String
  comment: String
  createdAt: DateTime
}

type Query {
  comments(documentId: String!): [Comment]
}

type Mutation {
  addComment(documentId: String!, comment: String!): Comment
  removeComment(commentId: String!): Comment
}
